//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvHistory
    {
        public int AdvHistoryId { get; set; }
        public int AdvId { get; set; }
        public int AdvRewardId { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
