//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvInfo
    {
        public int AdvId { get; set; }
        public string AdvTitle { get; set; }
        public int UserId { get; set; }
        public int AreaId { get; set; }
        public int TotalCount { get; set; }
        public decimal TotalCash { get; set; }
        public string ContentUrl { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> ModifyAt { get; set; }
        public string CostFeeUrl { get; set; }
        public decimal RemainderCash { get; set; }
    }
}
