//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int LoginHistoryId { get; set; }
        public int UserId { get; set; }
        public string IP { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
