//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MkmEntities : DbContext
    {
        public MkmEntities()
            : base("name=MkmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountHistory> AccountHistory { get; set; }
        public DbSet<AdvHistory> AdvHistory { get; set; }
        public DbSet<AdvInfo> AdvInfo { get; set; }
        public DbSet<AdvReward> AdvReward { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<AreaPosition> AreaPosition { get; set; }
        public DbSet<HistoryType> HistoryType { get; set; }
        public DbSet<LoginHistory> LoginHistory { get; set; }
        public DbSet<RechargeHistory> RechargeHistory { get; set; }
        public DbSet<RewardType> RewardType { get; set; }
        public DbSet<SystemConfig> SystemConfig { get; set; }
        public DbSet<SystemIncome> SystemIncome { get; set; }
        public DbSet<SystemStatus> SystemStatus { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserAccount> UserAccount { get; set; }
        public DbSet<SystemStatusCategory> SystemStatusCategory { get; set; }
        public DbSet<RechargeReward> RechargeReward { get; set; }
    }
}
