//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeReward
    {
        public int RechargeRewardId { get; set; }
        public decimal TargetValue { get; set; }
        public decimal RewardValue { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int Status { get; set; }
    }
}
