//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardType
    {
        public int RewardTypeId { get; set; }
        public decimal RewardValue { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int Status { get; set; }
    }
}
