//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public int ConfigId { get; set; }
        public decimal SystemIncomeValue { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
