//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemIncomeHistory
    {
        public int IncomeHistoryId { get; set; }
        public decimal IncomeValue { get; set; }
        public string ComeFrom { get; set; }
        public int SomeId { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
