//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public int ConfigId { get; set; }
        public decimal SystemIncomeValue { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
