//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> LastLoginIn { get; set; }
        public int Status { get; set; }
        public string MobilePhone { get; set; }
        public string Telephone { get; set; }
        public string CompanyName { get; set; }
        public string AccountName { get; set; }
        public string LegalPersonName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
    }
}
